# Generated by Django 4.2.20 on 2025-05-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technology'), ('BUSINESS', 'Business'), ('SCIENCE', 'Science'), ('HEALTH', 'Health'), ('SPORTS', 'Sports'), ('ENTERTAINMENT', 'Entertainment'), ('POLITICS', 'Politics'), ('WORLD', 'World News')], default='WORLD', max_length=20),
        ),
    ]
