# Generated by Django 4.2.20 on 2025-05-12 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_article_created_at_article_sentiment_article_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='news.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='news_usercl_user_id_8428c8_idx'), models.Index(fields=['article', 'timestamp'], name='news_usercl_article_cb4bbf_idx')],
            },
        ),
    ]
