# Generated by Django 4.2.20 on 2025-05-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred news categories'),
        ),
    ]
